export const LOGIN_ROUTE = 'login'
export const REGISTAR_ALUNO_ROUTE = 'registrarAluno'
export const PEDIDO_MATRICULA_ROUTE = '/'
export const EDITAR_PEDIDO_MATRICULA_ROUTE = 'editarPedidoMatricula'
export const NOT_FOUND_ROUTE = '/notFound'
